import { MigrationInterface, QueryRunner } from "typeorm";

export class InitialSync1754057954806 implements MigrationInterface {
    name = 'InitialSync1754057954806'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "notifications" DROP CONSTRAINT "FK_4d03b0b38074b109f71d27fb1c8"`);
        await queryRunner.query(`ALTER TABLE "notifications" DROP CONSTRAINT "FK_7f30bf6237f6d8c74823f183960"`);
        await queryRunner.query(`CREATE TYPE "public"."event_requests_status_enum" AS ENUM('pending', 'paid', 'failed', 'discrepancy')`);
        await queryRunner.query(`CREATE TABLE "event_requests" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "slug" character varying NOT NULL, "imageUrl" character varying(255) NOT NULL, "name" character varying(255) NOT NULL, "eventType" character varying(255) NOT NULL, "clientName" character varying(255) NOT NULL, "phoneNumber" character varying(20) NOT NULL, "pickupDate" date NOT NULL, "location" character varying(500) NOT NULL, "vehicle" character varying(255) NOT NULL, "hoursReserved" integer NOT NULL, "passengerCount" integer NOT NULL, "totalAmount" integer NOT NULL, "pendingAmount" integer NOT NULL, "depositAmount" integer NOT NULL, "equityDivision" integer NOT NULL, "status" "public"."event_requests_status_enum" NOT NULL DEFAULT 'pending', "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "deletedAt" TIMESTAMP, "host" character varying(255), "cohosts" character varying(255), "participants" character varying(255), "userId" uuid, CONSTRAINT "UQ_a4d5035722d6ccb887b6af4a3bd" UNIQUE ("slug"), CONSTRAINT "PK_af5567e19fbb4ffba2ee41fb7a0" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "event_messages" ("id" SERIAL NOT NULL, "message" character varying(255) NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "eventId" uuid, "userId" uuid, CONSTRAINT "PK_c7284d8b3497760777fc53e76b0" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "event_media" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "url" character varying(255) NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "eventId" uuid, "userId" uuid, CONSTRAINT "PK_4e5f0c8c1718c8c2026c15296af" PRIMARY KEY ("id"))`);
        await queryRunner.query(`ALTER TABLE "notifications" DROP COLUMN "triggeredById"`);
        await queryRunner.query(`ALTER TABLE "events" DROP COLUMN "status"`);
        await queryRunner.query(`DROP TYPE "public"."events_status_enum"`);
        await queryRunner.query(`ALTER TABLE "events" ADD "name" character varying(255) DEFAULT 'Untitled Event'`);
        await queryRunner.query(`UPDATE "events" SET "name" = 'Untitled Event' WHERE "name" IS NULL`);
        await queryRunner.query(`ALTER TABLE "events" ALTER COLUMN "name" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "events" ADD "imageUrl" character varying(255) DEFAULT ''`);
        await queryRunner.query(`UPDATE "events" SET "imageUrl" = '' WHERE "imageUrl" IS NULL`);
        await queryRunner.query(`ALTER TABLE "events" ALTER COLUMN "imageUrl" SET NOT NULL`);
        await queryRunner.query(`CREATE TYPE "public"."events_eventstatus_enum" AS ENUM('pending', 'finished', 'expired', 'started', 'discrepancy')`);
        await queryRunner.query(`ALTER TABLE "events" ADD "eventStatus" "public"."events_eventstatus_enum" NOT NULL DEFAULT 'pending'`);
        await queryRunner.query(`CREATE TYPE "public"."events_paymentstatus_enum" AS ENUM('pending', 'paid', 'failed', 'discrepancy')`);
        await queryRunner.query(`ALTER TABLE "events" ADD "paymentStatus" "public"."events_paymentstatus_enum" NOT NULL DEFAULT 'pending'`);
        await queryRunner.query(`ALTER TABLE "events" ADD "expiresAt" TIMESTAMP DEFAULT now() + interval '7 days'`);
        await queryRunner.query(`UPDATE "events" SET "expiresAt" = now() + interval '7 days' WHERE "expiresAt" IS NULL`);
        await queryRunner.query(`ALTER TABLE "events" ALTER COLUMN "expiresAt" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "event_participants" DROP CONSTRAINT "FK_d1b1a40ec360951071605b0f7a0"`);
        await queryRunner.query(`ALTER TABLE "event_participants" DROP CONSTRAINT "FK_4907f15416577c3bbbcd604d121"`);
        await queryRunner.query(`ALTER TABLE "event_participants" DROP COLUMN "userId"`);
        await queryRunner.query(`ALTER TABLE "event_participants" ADD "userId" uuid`);
        await queryRunner.query(`ALTER TABLE "event_participants" DROP COLUMN "eventId"`);
        await queryRunner.query(`ALTER TABLE "event_participants" ADD "eventId" uuid`);
        await queryRunner.query(`ALTER TABLE "event_feedback" DROP CONSTRAINT "FK_ceeb6fe53eb68ff475c56c4f37b"`);
        await queryRunner.query(`ALTER TABLE "event_feedback" DROP CONSTRAINT "FK_206a60ad96bb7e9d538f08fd7c1"`);
        await queryRunner.query(`ALTER TABLE "event_feedback" DROP CONSTRAINT "PK_45430c2b672fff2eef02db0fed1"`);
        await queryRunner.query(`ALTER TABLE "event_feedback" DROP COLUMN "id"`);
        await queryRunner.query(`ALTER TABLE "event_feedback" ADD "id" SERIAL NOT NULL`);
        await queryRunner.query(`ALTER TABLE "event_feedback" ADD CONSTRAINT "PK_45430c2b672fff2eef02db0fed1" PRIMARY KEY ("id")`);
        await queryRunner.query(`ALTER TABLE "event_feedback" DROP COLUMN "eventId"`);
        await queryRunner.query(`ALTER TABLE "event_feedback" ADD "eventId" uuid`);
        await queryRunner.query(`ALTER TABLE "event_feedback" DROP CONSTRAINT "REL_206a60ad96bb7e9d538f08fd7c"`);
        await queryRunner.query(`ALTER TABLE "event_feedback" DROP COLUMN "userId"`);
        await queryRunner.query(`ALTER TABLE "event_feedback" ADD "userId" uuid`);
        await queryRunner.query(`ALTER TABLE "event_feedback" ADD CONSTRAINT "UQ_206a60ad96bb7e9d538f08fd7c1" UNIQUE ("userId")`);
        await queryRunner.query(`ALTER TABLE "notifications" DROP CONSTRAINT "FK_692a909ee0fa9383e7859f9b406"`);
        await queryRunner.query(`ALTER TABLE "notifications" DROP CONSTRAINT "FK_3337493bfdc5d0fccd4bd5f51e3"`);
        await queryRunner.query(`ALTER TABLE "notifications" DROP COLUMN "userId"`);
        await queryRunner.query(`ALTER TABLE "notifications" ADD "userId" uuid`);
        await queryRunner.query(`ALTER TABLE "notifications" DROP COLUMN "eventId"`);
        await queryRunner.query(`ALTER TABLE "notifications" ADD "eventId" uuid`);
        await queryRunner.query(`ALTER TABLE "notifications" DROP COLUMN "requestId"`);
        await queryRunner.query(`ALTER TABLE "notifications" ADD "requestId" uuid`);
        await queryRunner.query(`ALTER TABLE "transactions" DROP CONSTRAINT "FK_b4e8825058f8818079bd936180b"`);
        await queryRunner.query(`ALTER TABLE "transactions" DROP CONSTRAINT "FK_6bb58f2b6e30cb51a6504599f41"`);
        await queryRunner.query(`ALTER TABLE "transactions" DROP CONSTRAINT "PK_a219afd8dd77ed80f5a862f1db9"`);
        await queryRunner.query(`ALTER TABLE "transactions" DROP COLUMN "id"`);
        await queryRunner.query(`ALTER TABLE "transactions" ADD "id" uuid NOT NULL DEFAULT uuid_generate_v4()`);
        await queryRunner.query(`ALTER TABLE "transactions" ADD CONSTRAINT "PK_a219afd8dd77ed80f5a862f1db9" PRIMARY KEY ("id")`);
        await queryRunner.query(`ALTER TABLE "transactions" DROP COLUMN "eventId"`);
        await queryRunner.query(`ALTER TABLE "transactions" ADD "eventId" uuid`);
        await queryRunner.query(`ALTER TABLE "transactions" DROP COLUMN "userId"`);
        await queryRunner.query(`ALTER TABLE "transactions" ADD "userId" uuid`);
        await queryRunner.query(`ALTER TABLE "events" DROP CONSTRAINT "PK_40731c7151fe4be3116e45ddf73"`);
        await queryRunner.query(`ALTER TABLE "events" DROP COLUMN "id"`);
        await queryRunner.query(`ALTER TABLE "events" ADD "id" uuid NOT NULL DEFAULT uuid_generate_v4()`);
        await queryRunner.query(`ALTER TABLE "events" ADD CONSTRAINT "PK_40731c7151fe4be3116e45ddf73" PRIMARY KEY ("id")`);
        await queryRunner.query(`ALTER TABLE "user_media" DROP CONSTRAINT IF EXISTS "FK_d77f9c7badfa3380b49a12a257f"`);
        await queryRunner.query(`DROP TABLE IF EXISTS "user_media"`);
        await queryRunner.query(`ALTER TABLE "users" DROP CONSTRAINT "PK_a3ffb1c0c8416b9fc6f907b7433"`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "id"`);
        await queryRunner.query(`ALTER TABLE "users" ADD "id" uuid NOT NULL DEFAULT uuid_generate_v4()`);
        await queryRunner.query(`ALTER TABLE "users" ADD CONSTRAINT "PK_a3ffb1c0c8416b9fc6f907b7433" PRIMARY KEY ("id")`);
        await queryRunner.query(`ALTER TABLE "invite_tokens" DROP CONSTRAINT "PK_5a05a43816424a1abac69e1f8a5"`);
        await queryRunner.query(`ALTER TABLE "invite_tokens" DROP COLUMN "id"`);
        await queryRunner.query(`ALTER TABLE "invite_tokens" ADD "id" uuid NOT NULL DEFAULT uuid_generate_v4()`);
        await queryRunner.query(`ALTER TABLE "invite_tokens" ADD CONSTRAINT "PK_5a05a43816424a1abac69e1f8a5" PRIMARY KEY ("id")`);
        await queryRunner.query(`ALTER TABLE "event_participants" ADD CONSTRAINT "FK_d1b1a40ec360951071605b0f7a0" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "event_participants" ADD CONSTRAINT "FK_4907f15416577c3bbbcd604d121" FOREIGN KEY ("eventId") REFERENCES "events"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "event_feedback" ADD CONSTRAINT "FK_ceeb6fe53eb68ff475c56c4f37b" FOREIGN KEY ("eventId") REFERENCES "events"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "event_feedback" ADD CONSTRAINT "FK_206a60ad96bb7e9d538f08fd7c1" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "event_requests" ADD CONSTRAINT "FK_1dd1c70703cb04eb9555c602363" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "notifications" ADD CONSTRAINT "FK_692a909ee0fa9383e7859f9b406" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "notifications" ADD CONSTRAINT "FK_3337493bfdc5d0fccd4bd5f51e3" FOREIGN KEY ("eventId") REFERENCES "events"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "notifications" ADD CONSTRAINT "FK_7f30bf6237f6d8c74823f183960" FOREIGN KEY ("requestId") REFERENCES "event_requests"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "transactions" ADD CONSTRAINT "FK_b4e8825058f8818079bd936180b" FOREIGN KEY ("eventId") REFERENCES "events"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "transactions" ADD CONSTRAINT "FK_6bb58f2b6e30cb51a6504599f41" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "event_messages" ADD CONSTRAINT "FK_8d1a21b35dbc31b360241f1396c" FOREIGN KEY ("eventId") REFERENCES "events"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "event_messages" ADD CONSTRAINT "FK_d59f7a8b3ee118db9a01462faea" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "event_media" ADD CONSTRAINT "FK_f62a0e8b1f64e2809fe4769eb17" FOREIGN KEY ("eventId") REFERENCES "events"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "event_media" ADD CONSTRAINT "FK_6dc89bea8f636d2473bf47bb133" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "event_media" DROP CONSTRAINT "FK_6dc89bea8f636d2473bf47bb133"`);
        await queryRunner.query(`ALTER TABLE "event_media" DROP CONSTRAINT "FK_f62a0e8b1f64e2809fe4769eb17"`);
        await queryRunner.query(`ALTER TABLE "event_messages" DROP CONSTRAINT "FK_d59f7a8b3ee118db9a01462faea"`);
        await queryRunner.query(`ALTER TABLE "event_messages" DROP CONSTRAINT "FK_8d1a21b35dbc31b360241f1396c"`);
        await queryRunner.query(`ALTER TABLE "transactions" DROP CONSTRAINT "FK_6bb58f2b6e30cb51a6504599f41"`);
        await queryRunner.query(`ALTER TABLE "transactions" DROP CONSTRAINT "FK_b4e8825058f8818079bd936180b"`);
        await queryRunner.query(`ALTER TABLE "notifications" DROP CONSTRAINT "FK_7f30bf6237f6d8c74823f183960"`);
        await queryRunner.query(`ALTER TABLE "notifications" DROP CONSTRAINT "FK_3337493bfdc5d0fccd4bd5f51e3"`);
        await queryRunner.query(`ALTER TABLE "notifications" DROP CONSTRAINT "FK_692a909ee0fa9383e7859f9b406"`);
        await queryRunner.query(`ALTER TABLE "event_requests" DROP CONSTRAINT "FK_1dd1c70703cb04eb9555c602363"`);
        await queryRunner.query(`ALTER TABLE "event_feedback" DROP CONSTRAINT "FK_206a60ad96bb7e9d538f08fd7c1"`);
        await queryRunner.query(`ALTER TABLE "event_feedback" DROP CONSTRAINT "FK_ceeb6fe53eb68ff475c56c4f37b"`);
        await queryRunner.query(`ALTER TABLE "event_participants" DROP CONSTRAINT "FK_4907f15416577c3bbbcd604d121"`);
        await queryRunner.query(`ALTER TABLE "event_participants" DROP CONSTRAINT "FK_d1b1a40ec360951071605b0f7a0"`);
        await queryRunner.query(`ALTER TABLE "invite_tokens" DROP CONSTRAINT "PK_5a05a43816424a1abac69e1f8a5"`);
        await queryRunner.query(`ALTER TABLE "invite_tokens" DROP COLUMN "id"`);
        await queryRunner.query(`ALTER TABLE "invite_tokens" ADD "id" SERIAL NOT NULL`);
        await queryRunner.query(`ALTER TABLE "invite_tokens" ADD CONSTRAINT "PK_5a05a43816424a1abac69e1f8a5" PRIMARY KEY ("id")`);
        await queryRunner.query(`ALTER TABLE "users" DROP CONSTRAINT "PK_a3ffb1c0c8416b9fc6f907b7433"`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "id"`);
        await queryRunner.query(`ALTER TABLE "users" ADD "id" SERIAL NOT NULL`);
        await queryRunner.query(`ALTER TABLE "users" ADD CONSTRAINT "PK_a3ffb1c0c8416b9fc6f907b7433" PRIMARY KEY ("id")`);
        await queryRunner.query(`ALTER TABLE "events" DROP CONSTRAINT "PK_40731c7151fe4be3116e45ddf73"`);
        await queryRunner.query(`ALTER TABLE "events" DROP COLUMN "id"`);
        await queryRunner.query(`ALTER TABLE "events" ADD "id" SERIAL NOT NULL`);
        await queryRunner.query(`ALTER TABLE "events" ADD CONSTRAINT "PK_40731c7151fe4be3116e45ddf73" PRIMARY KEY ("id")`);
        await queryRunner.query(`ALTER TABLE "transactions" DROP COLUMN "userId"`);
        await queryRunner.query(`ALTER TABLE "transactions" ADD "userId" integer`);
        await queryRunner.query(`ALTER TABLE "transactions" DROP COLUMN "eventId"`);
        await queryRunner.query(`ALTER TABLE "transactions" ADD "eventId" integer`);
        await queryRunner.query(`ALTER TABLE "transactions" DROP CONSTRAINT "PK_a219afd8dd77ed80f5a862f1db9"`);
        await queryRunner.query(`ALTER TABLE "transactions" DROP COLUMN "id"`);
        await queryRunner.query(`ALTER TABLE "transactions" ADD "id" SERIAL NOT NULL`);
        await queryRunner.query(`ALTER TABLE "transactions" ADD CONSTRAINT "PK_a219afd8dd77ed80f5a862f1db9" PRIMARY KEY ("id")`);
        await queryRunner.query(`ALTER TABLE "transactions" ADD CONSTRAINT "FK_6bb58f2b6e30cb51a6504599f41" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "transactions" ADD CONSTRAINT "FK_b4e8825058f8818079bd936180b" FOREIGN KEY ("eventId") REFERENCES "events"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "notifications" DROP COLUMN "requestId"`);
        await queryRunner.query(`ALTER TABLE "notifications" ADD "requestId" integer`);
        await queryRunner.query(`ALTER TABLE "notifications" DROP COLUMN "eventId"`);
        await queryRunner.query(`ALTER TABLE "notifications" ADD "eventId" integer`);
        await queryRunner.query(`ALTER TABLE "notifications" DROP COLUMN "userId"`);
        await queryRunner.query(`ALTER TABLE "notifications" ADD "userId" integer`);
        await queryRunner.query(`ALTER TABLE "notifications" ADD CONSTRAINT "FK_3337493bfdc5d0fccd4bd5f51e3" FOREIGN KEY ("eventId") REFERENCES "events"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "notifications" ADD CONSTRAINT "FK_692a909ee0fa9383e7859f9b406" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "event_feedback" DROP CONSTRAINT "UQ_206a60ad96bb7e9d538f08fd7c1"`);
        await queryRunner.query(`ALTER TABLE "event_feedback" DROP COLUMN "userId"`);
        await queryRunner.query(`ALTER TABLE "event_feedback" ADD "userId" integer`);
        await queryRunner.query(`ALTER TABLE "event_feedback" ADD CONSTRAINT "REL_206a60ad96bb7e9d538f08fd7c" UNIQUE ("userId")`);
        await queryRunner.query(`ALTER TABLE "event_feedback" DROP COLUMN "eventId"`);
        await queryRunner.query(`ALTER TABLE "event_feedback" ADD "eventId" integer`);
        await queryRunner.query(`ALTER TABLE "event_feedback" DROP CONSTRAINT "PK_45430c2b672fff2eef02db0fed1"`);
        await queryRunner.query(`ALTER TABLE "event_feedback" DROP COLUMN "id"`);
        await queryRunner.query(`ALTER TABLE "event_feedback" ADD "id" uuid NOT NULL DEFAULT uuid_generate_v4()`);
        await queryRunner.query(`ALTER TABLE "event_feedback" ADD CONSTRAINT "PK_45430c2b672fff2eef02db0fed1" PRIMARY KEY ("id")`);
        await queryRunner.query(`ALTER TABLE "event_feedback" ADD CONSTRAINT "FK_206a60ad96bb7e9d538f08fd7c1" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "event_feedback" ADD CONSTRAINT "FK_ceeb6fe53eb68ff475c56c4f37b" FOREIGN KEY ("eventId") REFERENCES "events"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "event_participants" DROP COLUMN "eventId"`);
        await queryRunner.query(`ALTER TABLE "event_participants" ADD "eventId" integer`);
        await queryRunner.query(`ALTER TABLE "event_participants" DROP COLUMN "userId"`);
        await queryRunner.query(`ALTER TABLE "event_participants" ADD "userId" integer`);
        await queryRunner.query(`ALTER TABLE "event_participants" ADD CONSTRAINT "FK_4907f15416577c3bbbcd604d121" FOREIGN KEY ("eventId") REFERENCES "events"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "event_participants" ADD CONSTRAINT "FK_d1b1a40ec360951071605b0f7a0" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "events" DROP COLUMN "expiresAt"`);
        await queryRunner.query(`ALTER TABLE "events" DROP COLUMN "paymentStatus"`);
        await queryRunner.query(`DROP TYPE "public"."events_paymentstatus_enum"`);
        await queryRunner.query(`ALTER TABLE "events" DROP COLUMN "eventStatus"`);
        await queryRunner.query(`DROP TYPE "public"."events_eventstatus_enum"`);
        await queryRunner.query(`ALTER TABLE "events" DROP COLUMN "imageUrl"`);
        await queryRunner.query(`ALTER TABLE "events" DROP COLUMN "name"`);
        await queryRunner.query(`CREATE TYPE "public"."events_status_enum" AS ENUM('pending', 'paid', 'failed', 'discrepancy')`);
        await queryRunner.query(`ALTER TABLE "events" ADD "status" "public"."events_status_enum" NOT NULL DEFAULT 'pending'`);
        await queryRunner.query(`ALTER TABLE "notifications" ADD "triggeredById" integer`);
        await queryRunner.query(`DROP TABLE "event_media"`);
        await queryRunner.query(`DROP TABLE "event_messages"`);
        await queryRunner.query(`DROP TABLE "event_requests"`);
        await queryRunner.query(`DROP TYPE "public"."event_requests_status_enum"`);
        await queryRunner.query(`ALTER TABLE "notifications" ADD CONSTRAINT "FK_7f30bf6237f6d8c74823f183960" FOREIGN KEY ("requestId") REFERENCES "eventrequests"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "notifications" ADD CONSTRAINT "FK_4d03b0b38074b109f71d27fb1c8" FOREIGN KEY ("triggeredById") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
    }

}
